export const config = {
    "PROXY": "https://genius-annotations-proxy.melonthug.workers.dev/?url=",
    "VERSION": "v1.2.0",
    "INSTALL_COMMAND": `iwr -useb "https://raw.githubusercontent.com/MelonThug/genius-annotations/refs/heads/main/install.ps1" | iex`,
    "TRACK_CHANGE_DEBOUNCE": 727, //WYSI
    "SONG_CACHE_TTL": 604800000, // 7 days
    "ANNOTATIONS_CACHE_TTL": 604800000, // 7 days
    "TRACK_CACHE_TTL": 259200000, // 3 days
    "SEARCH_CACHE_TTL": 86400000, // 1 day
    "TRACK_CACHE_THRESHOLD": 3,
    "GENIUS_LANGUAGE_MAP": {
        "aa": "Afar",
        "ab": "Аҧсуа",
        "af": "Afrikaans",
        "ak": "Akan",
        "am": "አማርኛ (Amharic)",
        "ar": "العربية",
        "as": "অসমীয়া",
        "ay": "Aymar",
        "az": "azərbaycan",
        "ba": "Башҡорт",
        "bal": "بلۏچی (Balochi)",
        "be": "Беларуская",
        "bg": "Български",
        "bh": "भोजपुरी",
        "bi": "Bislama",
        "bm": "bamanakan",
        "bn": "বাংলা",
        "bo": "བོད་ཡིག (Bod skad)",
        "br": "Brezhoneg",
        "bs": "bosanski",
        "bug": "ᨅᨔ ᨕᨘᨁᨗ (Basa Ugi)",
        "ca": "Català",
        "ceb": "Sinugboanong Binisaya",
        "chr": "ᏣᎳᎩ",
        "cnr": "crnogorski",
        "co": "Corsu",
        "crs": "Seselwa",
        "cs": "Česky",
        "cy": "Cymraeg",
        "da": "Dansk",
        "de": "Deutsch",
        "de-at": "Österreichisches Deutsch",
        "dv": "ދިވެހިބަސް",
        "dz": "རྫོང་ཁ",
        "egy": "Egyptian",
        "el": "Ελληνικά",
        "en": "English",
        "eo": "Esperanto",
        "es": "Español",
        "et": "Eesti",
        "eu": "Euskara",
        "fa": "فارسی",
        "fi": "Suomi",
        "fj": "Na Vosa Vakaviti",
        "fo": "Føroyskt",
        "fr": "Français",
        "fy": "Frysk",
        "ga": "Gaeilge",
        "gd": "Gàidhlig",
        "gl": "Galego",
        "gn": "Avañe'ẽ",
        "got": "gutisk",
        "gsw": "Schweizerdeutsch",
        "gu": "ગુજરાતી",
        "gv": "Gaelg",
        "ha": "هَوُسَ (Hausa)",
        "haw": "Hawai`i",
        "hi": "हिन्दी (Hindi)",
        "hmn": "Hmong",
        "hr": "hrvatski",
        "ht": "Krèyol ayisyen",
        "hu": "Magyar",
        "hy": "Հայերեն",
        "ia": "Interlingua",
        "id": "Bahasa Indonesia",
        "ie": "Interlingue",
        "ig": "Igbo",
        "ik": "Iñupiak",
        "is": "Íslenska",
        "it": "Italiano",
        "iu": "ᐃᓄᒃᑎᑐᑦ",
        "iw": "עברית (Hebrew)",
        "ja": "日本語 (Japanese)",
        "jam": "Patwah (Jamaican Patois)",
        "jw": "Javanese",
        "ka": "ქართული",
        "kea": "kriolu kabuverdianu",
        "kha": "Khasi",
        "kk": "Қазақша",
        "kl": "Kalaallisut",
        "km": "ភាសាខ្មែរ",
        "kn": "ಕನ್ನಡ",
        "ko": "한국어 (Korean)",
        "ks": "कॉशुर / کٲشُر",
        "ksh": "Kölsch",
        "ku": "Kurdî",
        "ky": "кыргызча (Kyrgyz)",
        "la": "lingua Latina (Latin)",
        "lb": "Lëtzebuergesch",
        "lg": "Luganda",
        "lif": "Limbu",
        "ln": "Lingála",
        "lo": "ລາວ (Lao)",
        "lt": "Lietuvių",
        "lv": "Latviešu",
        "mfe": "Mauritian Creole",
        "mg": "Malagasy",
        "mi": "Māori",
        "mk": "Македонски",
        "ml": "മലയാളം",
        "mn": "Монгол",
        "mr": "मराठी",
        "ms": "Bahasa Melayu",
        "mt": "bil-Malti",
        "my": "Myanmasa",
        "na": "Dorerin Naoero",
        "nap": "napoletano",
        "ne": "नेपाली",
        "nl": "Nederlands",
        "no": "Norsk",
        "non": "Old Norse",
        "nr": "isiNdebele",
        "nso": "Sesotho sa Leboa / Sepedi",
        "ny": "Chichewa",
        "oc": "Occitan",
        "om": "Oromoo",
        "or": "ଓଡ଼ିଆ",
        "pa": "ਪੰਜਾਬੀ",
        "pa-Arab": "پنجابی",
        "pl": "Polski",
        "ps": "پښتو",
        "pt": "Português",
        "qu": "Runa Simi",
        "rm": "rumantsch",
        "rn": "Kirundi",
        "ro": "Română",
        "rom": "rromani ćhib",
        "romanization": "Romanization",
        "rsk": "руски язик (Pannonian Rusyn)",
        "ru": "Русский (Russian)",
        "rw": "Kinyarwandi",
        "sa": "संस्कृतम्",
        "sah": "саха тыла (Sakha)",
        "sat": "ᱥᱟᱱᱛᱟᱲᱤ (Santali)",
        "scn": "sicilianu",
        "sco": "Scots",
        "sd": "सिंधी / سنڌي‎",
        "sg": "Sängö",
        "si": "සිංහල",
        "sk": "Slovenčina",
        "sl": "Slovenščina",
        "sm": "Gagana Samoa",
        "sn": "chiShona",
        "so": "Soomaaliga",
        "sq": "Shqip",
        "sr": "srpski",
        "ss": "SiSwati",
        "st": "Sesotho",
        "su": "Basa Sunda",
        "sv": "Svenska",
        "sw": "Kiswahili",
        "swb": "Shikomori",
        "syr": "Syriac",
        "ta": "தமிழ்",
        "te": "తెలుగు",
        "tg": "Тоҷикӣ",
        "th": "ไทย (Thai)",
        "ti": "ትግርኛ (Tigrinya)",
        "tk": "Туркмен / تركمن",
        "tl": "Filipino",
        "tlh": "tlhIngan-Hol",
        "tn": "Setswana",
        "to": "Lea Faka-Tonga",
        "tr": "Türkçe",
        "ts": "Xitsonga",
        "tt": "Татар (Tatar)",
        "ug": "Uyƣurqə / ئۇيغۇرچە",
        "uk": "Українська",
        "ur": "اردو",
        "uz": "o‘zbek",
        "ve": "Tshivenḓa",
        "vi": "Tiếng Việt",
        "vo": "Volapük",
        "war": "Waray",
        "wo": "Wolof",
        "xh": "isiXhosa",
        "yi": "ייִדיש (Yiddish)",
        "yo": "Yorùbá",
        "za": "Cuengh / Tôô / 壮语",
        "zh": "简体中文 (Simplified Chinese)",
        "zh-Hant": "繁體中文 (Traditional Chinese)",
        "zu": "isiZulu"
    }
}

